samples:
    WT_neg_siTDP2_5: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/testdata/WT_neg_siTDP2_5.chr21.fastq.gz
    WT_neg_siTDP2_6: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/testdata/WT_neg_siTDP2_6.chr21.fastq.gz
    WT_neg_siTDP2_1: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/testdata/WT_neg_siTDP2_1.chr21.fastq.gz
    WT_neg_siTDP2_3: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/testdata/WT_neg_siTDP2_3.chr21.fastq.gz
    WT_neg_siTDP2_2: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/testdata/WT_neg_siTDP2_2.chr21.fastq.gz
    WT_neg_siTDP2_4: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/testdata/WT_neg_siTDP2_4.chr21.fastq.gz

# Indices
star_index: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/work/db/1f5edf1dcf663db0189653efe5bb65/star
fai:        /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/work/88/a7ec7c7000fc1f505abdcd402f0ee6/genome.fa.fai
gff3:       /camp/lab/luscomben/home/users/jonesm5/2020_10_20_pum1/data/gencode.v35.annotation.gff3.gz

# Params
minreads: 2 # Minimum number of reads per polyA cluster to keep cluster
clusterdist: 200 # Distance between two clusters to merge
pas: 0.5
apa: 0.4
nopas: 0.3

# Scripts
randompriming:    /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/bin/remove_random_priming.R
annotateclusters: /camp/home/jonesm5/home/users/jonesm5/projects/nf-quantseq/bin/annotate_pas.R
