# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml

name: tdp43-mutants

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::pigz=2.3.4
  - bioconda::snakemake=5.31.1
  - bioconda::fastqc=0.11.9
  - bioconda::cutadapt=3.0
  - bioconda::star=2.7.4a
  - bioconda::samtools=1.11
  - bioconda::ucsc-bedsort=377
  - bioconda::ucsc-bedgraphtobigwig=377
  - bioconda::bedtools=2.29.2
  # - bioconda::salmon=1.4.0

# R packages
  - conda-forge::r-base
  - conda-forge::r-rmarkdown
  - conda-forge::r-data.table
  - conda-forge::r-r.utils
  - conda-forge::r-tictoc
  - conda-forge::r-optparse
  - conda-forge::r-pbapply
  - conda-forge::r-ggplot2
  - conda-forge::r-scales
  - conda-forge::r-cowplot
  - conda-forge::r-ggthemes
  - conda-forge::r-factoextra
  - conda-forge::r-zoo
  - conda-forge::r-cluster
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-pheatmap
  - conda-forge::r-ggforce
  - conda-forge::r-ggpubr
  - conda-forge::r-readxl

  - bioconda::bioconductor-rtracklayer
  - bioconda::bioconductor-genomicfeatures
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconda::bioconductor-drimseq
  - bioconda::bioconductor-biocparallel
